# ISO 3166-1 alpha-2 country codes, United States first then alphabetical.
COUNTRIES = [
  Tuple.new("US", "United States"),
  Tuple.new("AF", "Afghanistan"),
  Tuple.new("AL", "Albania"),
  Tuple.new("DZ", "Algeria"),
  Tuple.new("AS", "American Samoa"),
  Tuple.new("AD", "Andorra"),
  Tuple.new("AO", "Angola"),
  Tuple.new("AI", "Anguilla"),
  Tuple.new("AQ", "Antarctica"),
  Tuple.new("AG", "Antigua & Barbuda"),
  Tuple.new("AR", "Argentina"),
  Tuple.new("AM", "Armenia"),
  Tuple.new("AW", "Aruba"),
  Tuple.new("AC", "Ascension Island"),
  Tuple.new("AU", "Australia"),
  Tuple.new("AT", "Austria"),
  Tuple.new("AZ", "Azerbaijan"),
  Tuple.new("BS", "Bahamas"),
  Tuple.new("BH", "Bahrain"),
  Tuple.new("BD", "Bangladesh"),
  Tuple.new("BB", "Barbados"),
  Tuple.new("BY", "Belarus"),
  Tuple.new("BE", "Belgium"),
  Tuple.new("BZ", "Belize"),
  Tuple.new("BJ", "Benin"),
  Tuple.new("BM", "Bermuda"),
  Tuple.new("BT", "Bhutan"),
  Tuple.new("BO", "Bolivia"),
  Tuple.new("BA", "Bosnia & Herzegovina"),
  Tuple.new("BW", "Botswana"),
  Tuple.new("BV", "Bouvet Island"),
  Tuple.new("BR", "Brazil"),
  Tuple.new("IO", "British Indian Ocean Territory"),
  Tuple.new("VG", "British Virgin Islands"),
  Tuple.new("BN", "Brunei"),
  Tuple.new("BG", "Bulgaria"),
  Tuple.new("BF", "Burkina Faso"),
  Tuple.new("BI", "Burundi"),
  Tuple.new("KH", "Cambodia"),
  Tuple.new("CM", "Cameroon"),
  Tuple.new("CA", "Canada"),
  Tuple.new("IC", "Canary Islands"),
  Tuple.new("CV", "Cape Verde"),
  Tuple.new("BQ", "Caribbean Netherlands"),
  Tuple.new("KY", "Cayman Islands"),
  Tuple.new("CF", "Central African Republic"),
  Tuple.new("EA", "Ceuta & Melilla"),
  Tuple.new("TD", "Chad"),
  Tuple.new("CL", "Chile"),
  Tuple.new("CN", "China"),
  Tuple.new("CX", "Christmas Island"),
  Tuple.new("CP", "Clipperton Island"),
  Tuple.new("CC", "Cocos (Keeling) Islands"),
  Tuple.new("CO", "Colombia"),
  Tuple.new("KM", "Comoros"),
  Tuple.new("CG", "Congo - Brazzaville"),
  Tuple.new("CD", "Congo - Kinshasa"),
  Tuple.new("CK", "Cook Islands"),
  Tuple.new("CR", "Costa Rica"),
  Tuple.new("HR", "Croatia"),
  Tuple.new("CU", "Cuba"),
  Tuple.new("CW", "Curaçao"),
  Tuple.new("CY", "Cyprus"),
  Tuple.new("CZ", "Czechia"),
  Tuple.new("CI", "Côte d’Ivoire"),
  Tuple.new("DK", "Denmark"),
  Tuple.new("DG", "Diego Garcia"),
  Tuple.new("DJ", "Djibouti"),
  Tuple.new("DM", "Dominica"),
  Tuple.new("DO", "Dominican Republic"),
  Tuple.new("EC", "Ecuador"),
  Tuple.new("EG", "Egypt"),
  Tuple.new("SV", "El Salvador"),
  Tuple.new("GQ", "Equatorial Guinea"),
  Tuple.new("ER", "Eritrea"),
  Tuple.new("EE", "Estonia"),
  Tuple.new("SZ", "Eswatini"),
  Tuple.new("ET", "Ethiopia"),
  Tuple.new("EU", "European Union"),
  Tuple.new("EZ", "Eurozone"),
  Tuple.new("FK", "Falkland Islands"),
  Tuple.new("FO", "Faroe Islands"),
  Tuple.new("FJ", "Fiji"),
  Tuple.new("FI", "Finland"),
  Tuple.new("FR", "France"),
  Tuple.new("GF", "French Guiana"),
  Tuple.new("PF", "French Polynesia"),
  Tuple.new("TF", "French Southern Territories"),
  Tuple.new("GA", "Gabon"),
  Tuple.new("GM", "Gambia"),
  Tuple.new("GE", "Georgia"),
  Tuple.new("DE", "Germany"),
  Tuple.new("GH", "Ghana"),
  Tuple.new("GI", "Gibraltar"),
  Tuple.new("GR", "Greece"),
  Tuple.new("GL", "Greenland"),
  Tuple.new("GD", "Grenada"),
  Tuple.new("GP", "Guadeloupe"),
  Tuple.new("GU", "Guam"),
  Tuple.new("GT", "Guatemala"),
  Tuple.new("GG", "Guernsey"),
  Tuple.new("GN", "Guinea"),
  Tuple.new("GW", "Guinea-Bissau"),
  Tuple.new("GY", "Guyana"),
  Tuple.new("HT", "Haiti"),
  Tuple.new("HM", "Heard & McDonald Islands"),
  Tuple.new("HN", "Honduras"),
  Tuple.new("HK", "Hong Kong SAR China"),
  Tuple.new("HU", "Hungary"),
  Tuple.new("IS", "Iceland"),
  Tuple.new("IN", "India"),
  Tuple.new("ID", "Indonesia"),
  Tuple.new("IR", "Iran"),
  Tuple.new("IQ", "Iraq"),
  Tuple.new("IE", "Ireland"),
  Tuple.new("IM", "Isle of Man"),
  Tuple.new("IL", "Israel"),
  Tuple.new("IT", "Italy"),
  Tuple.new("JM", "Jamaica"),
  Tuple.new("JP", "Japan"),
  Tuple.new("JE", "Jersey"),
  Tuple.new("JO", "Jordan"),
  Tuple.new("KZ", "Kazakhstan"),
  Tuple.new("KE", "Kenya"),
  Tuple.new("KI", "Kiribati"),
  Tuple.new("XK", "Kosovo"),
  Tuple.new("KW", "Kuwait"),
  Tuple.new("KG", "Kyrgyzstan"),
  Tuple.new("LA", "Laos"),
  Tuple.new("LV", "Latvia"),
  Tuple.new("LB", "Lebanon"),
  Tuple.new("LS", "Lesotho"),
  Tuple.new("LR", "Liberia"),
  Tuple.new("LY", "Libya"),
  Tuple.new("LI", "Liechtenstein"),
  Tuple.new("LT", "Lithuania"),
  Tuple.new("LU", "Luxembourg"),
  Tuple.new("MO", "Macao SAR China"),
  Tuple.new("MG", "Madagascar"),
  Tuple.new("MW", "Malawi"),
  Tuple.new("MY", "Malaysia"),
  Tuple.new("MV", "Maldives"),
  Tuple.new("ML", "Mali"),
  Tuple.new("MT", "Malta"),
  Tuple.new("MH", "Marshall Islands"),
  Tuple.new("MQ", "Martinique"),
  Tuple.new("MR", "Mauritania"),
  Tuple.new("MU", "Mauritius"),
  Tuple.new("YT", "Mayotte"),
  Tuple.new("MX", "Mexico"),
  Tuple.new("FM", "Micronesia"),
  Tuple.new("MD", "Moldova"),
  Tuple.new("MC", "Monaco"),
  Tuple.new("MN", "Mongolia"),
  Tuple.new("ME", "Montenegro"),
  Tuple.new("MS", "Montserrat"),
  Tuple.new("MA", "Morocco"),
  Tuple.new("MZ", "Mozambique"),
  Tuple.new("MM", "Myanmar (Burma)"),
  Tuple.new("NA", "Namibia"),
  Tuple.new("NR", "Nauru"),
  Tuple.new("NP", "Nepal"),
  Tuple.new("NL", "Netherlands"),
  Tuple.new("NC", "New Caledonia"),
  Tuple.new("NZ", "New Zealand"),
  Tuple.new("NI", "Nicaragua"),
  Tuple.new("NE", "Niger"),
  Tuple.new("NG", "Nigeria"),
  Tuple.new("NU", "Niue"),
  Tuple.new("NF", "Norfolk Island"),
  Tuple.new("KP", "North Korea"),
  Tuple.new("MK", "North Macedonia"),
  Tuple.new("MP", "Northern Mariana Islands"),
  Tuple.new("NO", "Norway"),
  Tuple.new("OM", "Oman"),
  Tuple.new("QO", "Outlying Oceania"),
  Tuple.new("PK", "Pakistan"),
  Tuple.new("PW", "Palau"),
  Tuple.new("PS", "Palestinian Territories"),
  Tuple.new("PA", "Panama"),
  Tuple.new("PG", "Papua New Guinea"),
  Tuple.new("PY", "Paraguay"),
  Tuple.new("PE", "Peru"),
  Tuple.new("PH", "Philippines"),
  Tuple.new("PN", "Pitcairn Islands"),
  Tuple.new("PL", "Poland"),
  Tuple.new("PT", "Portugal"),
  Tuple.new("XA", "Pseudo-Accents"),
  Tuple.new("XB", "Pseudo-Bidi"),
  Tuple.new("PR", "Puerto Rico"),
  Tuple.new("QA", "Qatar"),
  Tuple.new("RO", "Romania"),
  Tuple.new("RU", "Russia"),
  Tuple.new("RW", "Rwanda"),
  Tuple.new("RE", "Réunion"),
  Tuple.new("WS", "Samoa"),
  Tuple.new("SM", "San Marino"),
  Tuple.new("CQ", "Sark"),
  Tuple.new("SA", "Saudi Arabia"),
  Tuple.new("SN", "Senegal"),
  Tuple.new("RS", "Serbia"),
  Tuple.new("SC", "Seychelles"),
  Tuple.new("SL", "Sierra Leone"),
  Tuple.new("SG", "Singapore"),
  Tuple.new("SX", "Sint Maarten"),
  Tuple.new("SK", "Slovakia"),
  Tuple.new("SI", "Slovenia"),
  Tuple.new("SB", "Solomon Islands"),
  Tuple.new("SO", "Somalia"),
  Tuple.new("ZA", "South Africa"),
  Tuple.new("GS", "South Georgia & South Sandwich Islands"),
  Tuple.new("KR", "South Korea"),
  Tuple.new("SS", "South Sudan"),
  Tuple.new("ES", "Spain"),
  Tuple.new("LK", "Sri Lanka"),
  Tuple.new("BL", "St. Barthélemy"),
  Tuple.new("SH", "St. Helena"),
  Tuple.new("KN", "St. Kitts & Nevis"),
  Tuple.new("LC", "St. Lucia"),
  Tuple.new("MF", "St. Martin"),
  Tuple.new("PM", "St. Pierre & Miquelon"),
  Tuple.new("VC", "St. Vincent & Grenadines"),
  Tuple.new("SD", "Sudan"),
  Tuple.new("SR", "Suriname"),
  Tuple.new("SJ", "Svalbard & Jan Mayen"),
  Tuple.new("SE", "Sweden"),
  Tuple.new("CH", "Switzerland"),
  Tuple.new("SY", "Syria"),
  Tuple.new("ST", "São Tomé & Príncipe"),
  Tuple.new("TW", "Taiwan"),
  Tuple.new("TJ", "Tajikistan"),
  Tuple.new("TZ", "Tanzania"),
  Tuple.new("TH", "Thailand"),
  Tuple.new("TL", "Timor-Leste"),
  Tuple.new("TG", "Togo"),
  Tuple.new("TK", "Tokelau"),
  Tuple.new("TO", "Tonga"),
  Tuple.new("TT", "Trinidad & Tobago"),
  Tuple.new("TA", "Tristan da Cunha"),
  Tuple.new("TN", "Tunisia"),
  Tuple.new("TM", "Turkmenistan"),
  Tuple.new("TC", "Turks & Caicos Islands"),
  Tuple.new("TV", "Tuvalu"),
  Tuple.new("TR", "Türkiye"),
  Tuple.new("UM", "U.S. Outlying Islands"),
  Tuple.new("VI", "U.S. Virgin Islands"),
  Tuple.new("UG", "Uganda"),
  Tuple.new("UA", "Ukraine"),
  Tuple.new("AE", "United Arab Emirates"),
  Tuple.new("GB", "United Kingdom"),
  Tuple.new("UN", "United Nations"),
  Tuple.new("ZZ", "Unknown Region"),
  Tuple.new("UY", "Uruguay"),
  Tuple.new("UZ", "Uzbekistan"),
  Tuple.new("VU", "Vanuatu"),
  Tuple.new("VA", "Vatican City"),
  Tuple.new("VE", "Venezuela"),
  Tuple.new("VN", "Vietnam"),
  Tuple.new("WF", "Wallis & Futuna"),
  Tuple.new("EH", "Western Sahara"),
  Tuple.new("YE", "Yemen"),
  Tuple.new("ZM", "Zambia"),
  Tuple.new("ZW", "Zimbabwe"),
  Tuple.new("AX", "Åland Islands"),
]
